version: 2.1
jobs:
  deploy-backend:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"
      - run:
          name: Update and upgrade packages
          command: ssh ${USER}@${HOST} 'sudo apt-get update && sudo apt-get upgrade -y'
