version: 2.1
jobs:
  deploy-backend:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0d:71:f6:fe:2e:58:1a:9b:65:68:bc:9c:40:a2:49:03"
            - "af:ee:bd:e7:30:b5:72:ac:84:49:b7:d3:fa:e8:e1:a8"
      - run:
          name: Install packages required by deployment
          command: apt-get update && apt-get install -y openssh-client
      - run:
          name: Add host to known hosts
          command: ssh-keyscan ${HOST} >> ~/.ssh/known_hosts
      - run:
          name: Update packages
          command: ssh ${USER}@${HOST} 'sudo apt-get update' 2>&1
          no_output_timeout: 3m
      - run:
          name: Create deployment directory
          command: ssh ${USER}@${HOST} 'mkdir -p /opt/deployments/${BACKEND_APP_NAME}'
      - run:
          name: Install Python
          command: ssh ${USER}@${HOST} 'command -v python3 &>/dev/null || sudo apt-get install -y python3'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-backend
