# Generated by Django 4.2.5 on 2023-10-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250)),
                ('localization_key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('hierarchynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mathbackend.hierarchynode')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mathbackend.category')),
            ],
            bases=('mathbackend.hierarchynode',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('hierarchynode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mathbackend.hierarchynode')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathbackend.category')),
            ],
            bases=('mathbackend.hierarchynode',),
        ),
    ]
