# Generated by Django 4.2.5 on 2023-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='filename',
            field=models.CharField(default='error404', max_length=250),
        ),
    ]
