# Generated by Django 5.0 on 2023-12-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathbackend', '0003_remove_category_localization_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='admin_name',
        ),
    ]
